"""初始化测试的数据库

Revision ID: ce100cc3f9d5
Revises: 
Create Date: 2021-04-13 15:58:09.065610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ce100cc3f9d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_article',
    sa.Column('id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='作者id'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='文章分类'),
    sa.Column('article_cover', sa.String(length=1024), server_default=sa.text('NULL::character varying'), nullable=True, comment='文章缩略图地址'),
    sa.Column('article_title', sa.String(length=50), nullable=False, comment='文章标题'),
    sa.Column('article_content', sa.Text(), nullable=False, comment='文章内容'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('NULL::timestamp without time zone'), nullable=True, comment='发表时间'),
    sa.Column('update_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('NULL::timestamp without time zone'), nullable=True),
    sa.Column('is_top', sa.SmallInteger(), nullable=True, comment='是否置顶'),
    sa.Column('is_draft', sa.SmallInteger(), server_default=sa.text('0'), nullable=True, comment='是否为草稿'),
    sa.Column('is_delete', sa.SmallInteger(), server_default=sa.text('0'), nullable=True, comment='是否删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章结构表'
    )
    op.create_index('fk_title_content', 'tb_article', ['article_title', 'article_content'], unique=False)
    op.create_index(op.f('ix_tb_article_category_id'), 'tb_article', ['category_id'], unique=False)
    op.create_index(op.f('ix_tb_article_user_id'), 'tb_article', ['user_id'], unique=False)
    op.create_table('tb_article_tag',
    sa.Column('id', sa.Integer(), nullable=False, comment='文章 标签关系id'),
    sa.Column('article_id', sa.Integer(), nullable=False, comment='文章id'),
    sa.Column('tag_id', sa.Integer(), nullable=False, comment='标签id'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章 标签关系表'
    )
    op.create_index(op.f('ix_tb_article_tag_article_id'), 'tb_article_tag', ['article_id'], unique=False)
    op.create_index(op.f('ix_tb_article_tag_tag_id'), 'tb_article_tag', ['tag_id'], unique=False)
    op.create_table('tb_blog_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('about_content', sa.Text(), nullable=False, comment='关于我的内容'),
    sa.PrimaryKeyConstraint('id'),
    comment='博客简介信息表'
    )
    op.create_table('tb_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=20), nullable=False, comment='分类名'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('NULL::timestamp without time zone'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章分类对象表'
    )
    op.create_table('tb_comment',
    sa.Column('id', sa.Integer(), nullable=False, comment='评论唯一id'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='评论用户id'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='评论文章id'),
    sa.Column('comment_content', sa.Text(), nullable=False, comment='评论内容'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), nullable=False, comment='评论时间'),
    sa.Column('replay_id', sa.Integer(), nullable=True, comment='回复用户id'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父评论id'),
    sa.Column('is_delete', sa.SmallInteger(), server_default=sa.text('0'), nullable=True, comment='是否删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='评论内容表'
    )
    op.create_index(op.f('ix_tb_comment_article_id'), 'tb_comment', ['article_id'], unique=False)
    op.create_index(op.f('ix_tb_comment_parent_id'), 'tb_comment', ['parent_id'], unique=False)
    op.create_index(op.f('ix_tb_comment_user_id'), 'tb_comment', ['user_id'], unique=False)
    op.create_table('tb_friend_link',
    sa.Column('id', sa.Integer(), nullable=False, comment='友情链接唯一id'),
    sa.Column('link_name', sa.String(length=20), nullable=False, comment='链接名'),
    sa.Column('link_avatar', sa.String(length=255), nullable=False, comment='链接头像'),
    sa.Column('link_address', sa.String(length=50), nullable=False, comment='链接地址'),
    sa.Column('link_intro', sa.String(length=50), nullable=False, comment='链接介绍'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), nullable=False, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='友情连接表'
    )
    op.create_index(op.f('ix_tb_friend_link_link_name'), 'tb_friend_link', ['link_name'], unique=False)
    op.create_table('tb_message',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
    sa.Column('ip_address', sa.String(length=50), nullable=False, comment='用户ip'),
    sa.Column('ip_source', sa.String(length=255), nullable=False, comment='用户地址'),
    sa.Column('nickname', sa.String(length=255), nullable=False, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=False, comment='头像'),
    sa.Column('message_content', sa.String(length=255), nullable=False, comment='留言内容'),
    sa.Column('time', sa.SmallInteger(), nullable=False, comment='弹幕速度'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), nullable=False, comment='发布时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='Message表'
    )
    op.create_table('tb_tag',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
    sa.Column('tag_name', sa.String(length=20), nullable=False, comment='标签名'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('NULL::timestamp without time zone'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章标签表'
    )
    op.create_table('tb_unique_view',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), nullable=False, comment='时间'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='访问量'),
    sa.PrimaryKeyConstraint('id'),
    comment='访问量表'
    )
    op.create_table('tb_user_auth',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键id'),
    sa.Column('user_info_id', sa.Integer(), nullable=False, comment='用户信息id'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('password', sa.String(length=100), nullable=False, comment='密码'),
    sa.Column('login_type', sa.SmallInteger(), nullable=False, comment='登陆类型'),
    sa.Column('ip_addr', sa.String(length=50), server_default=sa.text('NULL::character varying'), nullable=True, comment='用户登录ip'),
    sa.Column('ip_source', sa.String(length=50), server_default=sa.text('NULL::character varying'), nullable=True, comment='ip来源'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), nullable=False, comment='创建时间'),
    sa.Column('last_login_time', postgresql.TIMESTAMP(precision=0), server_default=sa.text('NULL::timestamp without time zone'), nullable=True, comment='上次登录时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户认证表'
    )
    op.create_table('tb_user_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='用户id'),
    sa.Column('user_role', sa.String(length=20), server_default=sa.text("'user'::character varying"), nullable=True, comment='用户角色'),
    sa.Column('nickname', sa.String(length=20), nullable=False, comment='用户昵称'),
    sa.Column('avatar', sa.String(length=1024), nullable=False, comment='用户头像[链接]'),
    sa.Column('intor', sa.String(length=255), server_default=sa.text('NULL::character varying'), nullable=True, comment='用户简介'),
    sa.Column('web_site', sa.String(length=255), server_default=sa.text('NULL::character varying'), nullable=True, comment='个人网站'),
    sa.Column('create_time', postgresql.TIMESTAMP(precision=0), nullable=False, comment='创建时间'),
    sa.Column('is_silence', sa.SmallInteger(), server_default=sa.text('0'), nullable=True, comment='是否禁言'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户信息表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user_info')
    op.drop_table('tb_user_auth')
    op.drop_table('tb_unique_view')
    op.drop_table('tb_tag')
    op.drop_table('tb_message')
    op.drop_index(op.f('ix_tb_friend_link_link_name'), table_name='tb_friend_link')
    op.drop_table('tb_friend_link')
    op.drop_index(op.f('ix_tb_comment_user_id'), table_name='tb_comment')
    op.drop_index(op.f('ix_tb_comment_parent_id'), table_name='tb_comment')
    op.drop_index(op.f('ix_tb_comment_article_id'), table_name='tb_comment')
    op.drop_table('tb_comment')
    op.drop_table('tb_category')
    op.drop_table('tb_blog_info')
    op.drop_index(op.f('ix_tb_article_tag_tag_id'), table_name='tb_article_tag')
    op.drop_index(op.f('ix_tb_article_tag_article_id'), table_name='tb_article_tag')
    op.drop_table('tb_article_tag')
    op.drop_index(op.f('ix_tb_article_user_id'), table_name='tb_article')
    op.drop_index(op.f('ix_tb_article_category_id'), table_name='tb_article')
    op.drop_index('fk_title_content', table_name='tb_article')
    op.drop_table('tb_article')
    # ### end Alembic commands ###
