"""修改字段名错误问题

Revision ID: f61da4087031
Revises: ce100cc3f9d5
Create Date: 2021-05-18 14:17:02.062652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61da4087031'
down_revision = 'ce100cc3f9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_comment', sa.Column('reply_id', sa.Integer(), nullable=True, comment='回复用户id'))
    op.drop_column('tb_comment', 'replay_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_comment', sa.Column('replay_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='回复用户id'))
    op.drop_column('tb_comment', 'reply_id')
    # ### end Alembic commands ###
